name: Build the images
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - build.sh
      - Dockerfile
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ github.repository_owner }}/mplabx-xc8:latest
          cache-from: type=registry,ref=${{ github.repository_owner }}/mplabx-xc8:latest
          cache-to: type=inline
          platforms: linux/amd64
      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
