name: Build the images
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - build.sh
      - Dockerfile
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v3.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jeandeaual/mplabx-xc8:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64
      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
