name: Update DockerHub description
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/update-description.yml
      - README.md
jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Update DockerHub repository description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository_owner }}/mplabx-xc8
